version: "3.8"

services:
  backend:
    build: 
      context: .
      dockerfile: Dockerfile  # Ensure this matches the actual Dockerfile name
    container_name: "IRNet-backend"
    tty: true
    ports:
      - "127.0.0.1:9900:9900"
    environment:
      - FLASK_ENV=development
    volumes:
      - ./app:/app  # Mount the host's `./app` directory to the container's `/app` directory
    networks:
      # - default
      - kbc-net

networks:
  kbc-net:
    external: true

