# version: "3.8"

# services:

#   web:
#     build: 
#       context: .
#       dockerfile: DockerFile
#     container_name: "irnet-backend"
#     tty: true
#     restart: always 
#     command: flask run --host=0.0.0.0:9900
#     volumes:
#       - .:/usr/src/app
#     ports:
#       - "9900:9900"
#     networks:
#       - default
#       - kbc-net

# networks:
#   kbc-net:
#     external: true

version: "3.8"

services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile  # Ensure this matches the actual Dockerfile name
    container_name: "IRNet-backend"
    tty: true
    ports:
      - "9900:9900"
    environment:
      - PORT=9900
    networks:
      - default
      - kbc-net

networks:
  kbc-net:
    external: true
